### ISSUE TITLE
Benefits over Basher or bpkg?

### ISSUE THREAD

**Issue by basejump** [hyperupcall/basalt#99]
Stumbled on your project and it looks intriguing. 
Would be helpful to put a comparison or benefits section in README to give a quick list of the why and what vs the others. 
I think I see one main one in the centralized location it puts everything. is that the primary difference?

**Comment by hyperupcall** [comment]
I think I have that in [Motivation](https://github.com/hyperupcall/basalt/blob/a68e036ce90b444c6c2385fd3da5af5c69ef7e0d/docs/internals/motivation.md), is that what you're looking for?

It's kind of out of date and doesn't mention some of the features in the README, so I guess I should add those things soon

**Comment by hyperupcall** [comment]
To be honest, I sort of forgot how basher or bpkg works since It's been so long, so I can't really answer your question specifically - but I can say this:

- It's really efficient when downloading packages. It only downloads one version of a package at a time - if it already exists it doesn't download it. (Akin to [pnpm](https://pnpm.io) in the nodejs ecosystem, which is significantly faster compared to npm)
- Basalt is made _specifically_ for per-project / local dependencies. Basher and bpkg started out as global installers, and basher sort of supports local projects, but I think you have to do weird things with environment variables and it doesn't work very well
- Basalt automatically loads all dependencies. For example, if you specify [this line](https://github.com/hyperupcall/woof/blob/a8c8276fdf330920ff343ba778cee9718bcb4593/basalt.toml) in your package config, and properly call a few Basalt commands/functions [like so](https://github.com/hyperupcall/woof/blob/main/pkg/bin/woof) in your entry point, all the dependencies will be sourced and ready to use. A library I use in nearly all my Bash projects is [bash-core](https://github.com/hyperupcall/bash-core) - it's quite useful and provides stack traces, enhancements to `trap` and `shopt`, and common printing functions. This sort of [ecosystem and wide breadth of libraries](https://github.com/hyperupcall/awesome-basalt) doesn't really exist with either Basher or bpkg
- Niceties like project initialization (iirc `basalt init --type=app`) (like `npm init`, etc.), like nearly all other package managers
- Basalt _rarely_ calls out to external programs and instead relies on pure Bash. This makes everything feel _much_ snappier (no exec overhead)
- If a package is globally installable by bpkg or Basher, it will (read: should) Just Work with Basalt

The main disadvantage of Basalt is that it's not stable - it hasn't had a release in white a while yet. This is because I've been working on supporting libraries like [bash-object](https://github.com/hyperupcall/bash-object), [bash-args](https://github.com/hyperupcall/bash-args), [bash-algo](https://github.com/hyperupcall/bash-algo), [bash-term](https://github.com/hyperupcall/bash-term), [etc](https://github.com/hyperupcall/awesome-basalt) and doing other things. My hope is once I release bash-json, system for typechecking Bash code, and fixing a bunch of the known bugs with Basalt, Basalt will be ready for a `v1.0.0` release. I don't know when that will be though

**Comment by basejump** [comment]
thanks for the update. yes, the Motivation does answer some, missed that when I was scanning.
